require("dotenv").config();
const { sequelize } = require("./config/db/postgres");
const eventModel = require("./models/postgres/eventModel");

const seedEvents = async () => {
  try {
    await sequelize.authenticate();
    console.log("Connected to PostgreSQL for event seeding...");

    // Synchronize model schema changes
    await sequelize.sync();

    const eventsData = [
      {
        name: "Blind Coding",
        description: "Code under progressively tightening visual constraints; a tie-break mini-event awards bonus points.",
        category: "TECHNICAL",
        team_type: "INDIVIDUAL",
        min_team_size: 1,
        max_team_size: 1,
        day: 18,
        date: "2026-09-18",
        start_time: "09:30:00",
        end_time: "11:30:00",
        venue: "CC Lab 1",
        max_participants: 60,
        is_flagship: false,
        guardian_asset: "/assets/guardians/veil.svg",
        entry_fee: 0.0,
        status: "open",
      },
      {
        name: "CodeXcape",
        description: "A technical escape room — a quiz round plus timed coding challenges unlock a six-digit escape code.",
        category: "TECHNICAL",
        team_type: "TEAM",
        min_team_size: 2,
        max_team_size: 3,
        day: 18,
        date: "2026-09-18",
        start_time: "11:30:00",
        end_time: "13:30:00",
        venue: "CC Lab 2",
        max_participants: 40,
        is_flagship: false,
        guardian_asset: "/assets/guardians/vaultwarden.svg",
        entry_fee: 0.0,
        status: "open",
      },
      {
        name: "Debug Arena",
        description: "Find, fix and optimise faulty programs against the clock.",
        category: "TECHNICAL",
        team_type: "INDIVIDUAL",
        min_team_size: 1,
        max_team_size: 1,
        day: 18,
        date: "2026-09-18",
        start_time: "14:00:00",
        end_time: "16:00:00",
        venue: "CC Lab 3",
        max_participants: 80,
        is_flagship: false,
        guardian_asset: "/assets/guardians/fracture.svg",
        entry_fee: 0.0,
        status: "open",
      },
      {
        name: "Extraction",
        description: "A story-driven cybersecurity CTF: crypto, auth and forensic challenges to stop Operation BLACKOUT.",
        category: "TECHNICAL",
        team_type: "TEAM",
        min_team_size: 2,
        max_team_size: 4,
        day: 18,
        date: "2026-09-18",
        start_time: "14:00:00",
        end_time: "17:00:00",
        venue: "Security Lab",
        max_participants: 50,
        is_flagship: false,
        guardian_asset: "/assets/guardians/blackout-9.svg",
        entry_fee: 0.0,
        status: "open",
      },
      {
        name: "Project Phoenix: System Recovery",
        description: "A software-engineering simulation — Recovery Squads restore critical systems after a catastrophic production failure.",
        category: "TECHNICAL",
        team_type: "TEAM",
        min_team_size: 2,
        max_team_size: 3,
        day: 19,
        date: "2026-09-19",
        start_time: "09:30:00",
        end_time: "12:30:00",
        venue: "Systems Lab",
        max_participants: 45,
        is_flagship: false,
        guardian_asset: "/assets/guardians/pyre-01.svg",
        entry_fee: 0.0,
        status: "open",
      },
      {
        name: "Code Relay",
        description: "Two-member teams solve problems while swapping coders every five minutes.",
        category: "TECHNICAL",
        team_type: "TEAM",
        min_team_size: 2,
        max_team_size: 2,
        day: 19,
        date: "2026-09-19",
        start_time: "10:00:00",
        end_time: "12:00:00",
        venue: "CC Lab 4",
        max_participants: 50,
        is_flagship: false,
        guardian_asset: "/assets/guardians/tandem.svg",
        entry_fee: 0.0,
        status: "open",
      },
      {
        name: "In The Slot",
        description: "An IPL-style auction: cricket knowledge, budgeting, psychology and fast decisions.",
        category: "NON_TECHNICAL",
        team_type: "TEAM",
        min_team_size: 2,
        max_team_size: 4,
        day: 18,
        date: "2026-09-18",
        start_time: "10:00:00",
        end_time: "13:00:00",
        venue: "MCA Seminar Hall",
        max_participants: 60,
        is_flagship: false,
        guardian_asset: "/assets/guardians/gavelon.svg",
        entry_fee: 0.0,
        status: "open",
      },
      {
        name: "Hunt Your Treasure — QR Escape Challenge",
        description: "Solve clues, scan hidden QR codes, answer MCA and GK questions to unlock the next stage.",
        category: "NON_TECHNICAL",
        team_type: "TEAM",
        min_team_size: 2,
        max_team_size: 4,
        day: 19,
        date: "2026-09-19",
        start_time: "10:00:00",
        end_time: "13:00:00",
        venue: "Campus Wide",
        max_participants: 100,
        is_flagship: false,
        guardian_asset: "/assets/guardians/qrux.svg",
        entry_fee: 0.0,
        status: "open",
      },
      {
        name: "NOSTOS: The Journey Home",
        description: "Sail Odysseus's trials through riddles, logic, wordplay and patterns on a live world map.",
        category: "NON_TECHNICAL",
        team_type: "TEAM",
        min_team_size: 2,
        max_team_size: 3,
        day: 19,
        date: "2026-09-19",
        start_time: "13:30:00",
        end_time: "16:30:00",
        venue: "Assembly Hall",
        max_participants: 75,
        is_flagship: false,
        guardian_asset: "/assets/guardians/helmsman.svg",
        entry_fee: 0.0,
        status: "open",
      },
      {
        name: "Pixel Paradox: AI or Reality?",
        description: "Tell AI-generated media from authentic content — observation, reasoning and AI awareness.",
        category: "TECHNICAL",
        team_type: "INDIVIDUAL",
        min_team_size: 1,
        max_team_size: 1,
        day: 18,
        date: "2026-09-18",
        start_time: "15:00:00",
        end_time: "17:00:00",
        venue: "Multimedia Lab",
        max_participants: 90,
        is_flagship: false,
        guardian_asset: "/assets/guardians/simulacra.svg",
        entry_fee: 0.0,
        status: "open",
      },
      {
        name: "Star of LOGIN",
        description: "The headline event of LOGIN 2026 — the last mind standing.",
        category: "TECHNICAL",
        team_type: "INDIVIDUAL",
        min_team_size: 1,
        max_team_size: 1,
        day: 19,
        date: "2026-09-19",
        start_time: "14:00:00",
        end_time: "17:30:00",
        venue: "Main Auditorium",
        max_participants: 120,
        is_flagship: true,
        guardian_asset: "/assets/guardians/the_last_standing.svg",
        entry_fee: 0.0,
        status: "open",
      },
    ];

    for (const event of eventsData) {
      const [record, created] = await eventModel.findOrCreate({
        where: { name: event.name },
        defaults: event,
      });

      if (!created) {
        await record.update(event);
      }
    }

    console.log("Successfully seeded 11 official LOGIN 2026 events!");
    process.exit(0);
  } catch (error) {
    console.error("Failed to seed LOGIN 2026 events:", error);
    process.exit(1);
  }
};

seedEvents();
